services:
  web:
    build: .
    container_name: bus-line-segmentation-barcelona
    ports:
      - "8082:8082"
    environment:
      - PYTHONUNBUFFERED=1
  ors-app:
    container_name: ors-app-barcelona
    ports:
      - "8085:8080"
      - "9005:9000"
    image: openrouteservice/openrouteservice:v7.1.0
    user: "${UID:-0}:${GID:-0}"
#    build:
#      context: ../
#      args:
#        ORS_CONFIG: ./openrouteservice/src/main/resources/ors-config-sample.json
#        OSM_FILE: ./openrouteservice/src/main/files/heidelberg.osm.gz
    volumes:
      - ./openrouteservice/docker/graphs:/home/ors/ors-core/data/graphs
      - ./openrouteservice/docker/elevation_cache:/home/ors/ors-core/data/elevation_cache
      - ./openrouteservice/docker/logs/ors:/home/ors/ors-core/logs/ors
      - ./openrouteservice/docker/logs/tomcat:/home/ors/tomcat/logs
      - ./openrouteservice/docker/conf:/home/ors/ors-conf
      - ./openrouteservice/docker/cataluna-latest.osm.pbf:/home/ors/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=True  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"



  